### ISSUE TITLE
一些小小小的小建议-拖动位置改到顶部

### ISSUE THREAD

**Issue by luiguangguan** [orangelckc/bili-message#1]
### 但是
![image](https://github.com/orangelckc/bili-message/assets/20753694/d8fee8dd-ec55-419f-9039-004c5843da17)

**1. 这里的拖动提示在我的显示器对比度非常不明显，可以考虑想传统那样放在顶部，并用稍稍暗调区分可拖动区域。符合习惯**

**2. 另外可以支持多个直播间，且可以备注直播间**
**3. 可以自由切换直播间，并且记录弹幕历史。**

**Comment by orangelckc** [comment]
![image](https://github.com/orangelckc/bili-message/assets/48410934/b0284ca0-d4f7-4716-a67c-c33c1897c573)
已添加对应的功能
